<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>AreaRec.Capture</AssemblyName>
    <RootNamespace>AreaRec.Capture</RootNamespace>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AreaRec.Core\AreaRec.Core.csproj" />
  </ItemGroup>
</Project>
